language: java
script:
- "./gradlew jar distZip"
notifications:
  hipchat:
    rooms:
      secure: a+Z+kNPc7cHUmQyVZZW9PBL5TYoDOGLZvjvbJeih4Z3hkK1jWkI1Vb7hy76yoMtGXhutgswmpn8GES4MbLC8kdyy8E+yDCPcl9f+axFE9mPFGpUSbl4pEjjeQ7+uH2Z60WOINX1SQ0V1pdN1kD/J+2P6ykKR0G17TIgH7JuRwWxM+G8UWAPx4bykKIpNMn9opxGJ4qr/cPZF15Wiz18XcGlhjDeAym2ntjB3ZnTi3Wv8kCkcG4SdIpMg7BJszq941NOkgZX+1rHzJhliIT6N3g2dhxlLiPBPsvBSARD0Q4lStriR1HwupBPNVYwPqIprVlxhduqd2L+ejt4p/Av+RfU4w4PIQ54Pa8hMEjp1oNGk2QKEEhaVQlp0o4+9yO1qcti6iqaKNC9AIAB8puF/X6Rno1TyVLVxTvHe0lFg/t4m4Vy8abUP/gp0dyy5mFIGbuivr4MS6mO8CsKVtHiLCqv5A0jyRhktXU1vCGa6pbwQZciABFWGhht1g1nal6/FrkgGbEgAtUOfAfnYpaZ339H9l9HtkMK8puHbqlP22JB2x6ZEUM/GiroVfhGrgbNK5cFCMNenK/Wdg1oiJwNW3kgqxjddPsmlnb1SGdfUXyIWxlD1qpV36WdMH9REbrYb6O6RystTlA8btRwrptBG6Iiu90PhjRM0BVPV9QAPfn8=
deploy:
  provider: releases
  api_key:
    secure: MZ3jJgZ7O2LzCC2a7efcOlpIVJPJEtnmVCM5EOlP6a+hUk+4lIXXPq8L1m6c71Hcgh1+dsMkTnu7eQfc2RrPUe5B+oiE9AcjLu9cH7pW3bc/bhhlkhE1kAz56CJDHoboyhmGRodklanl0wustDqxOmLn3XtlGSpojld4wiY4/S6bMQrQ0cJhkH9nLD331j5CbqoAxK6mZunECTKS1VVMj3Xaui5KqYPtCHnm2dAw6Hl3SIQf39AnWuqUfysh/A1rcYK0frKtb55eE+KjVtDm9rIq6qKoGqG2gYxQAlHo/4qjaCVcBA1b8f6f8Qa+i6aQTpVFQSx+WyZsO2MnIeI/AxmtYm4VadlecPmMRwZY/ZOFpdPY0HATjdzYjgYzx3HmhdoqY0qbE2E6fPdT3cYwdlojEr4CNxPux2bzE8oIEOW0hBj+2DCg8y5b0+d0dBYlyfOikUblZQaBX0KeOgqY/oykYw8Ti9jD8kpddS7vEUTUvlqGtDXBbVAQ4Vw8+/+K2dRnAs5zSocMtNFmxJZVqL9CKAEvQ3YlKl78pibjGohn/88OJvVse2/R7psPSgpISmU8ags+nmw/cLuNKZkaLTCMxJ+p9w3yDhNfW8ZYIC6hNBtMfz2C3PoJlbAeEiEAxY3tmKkIgqT2fjBEKnMcsVIHIz+/edFeVC8woGvcYuE=
  file: build/distributions/xlr-perforce-changelist-trigger-plugin-2.0.0.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-perforce-changelist-trigger-plugin

